SaleWebsite/config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get  "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  root "static_pages#home"
   resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SaleWebsite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

SaleWebsite/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format:{ with: VALID_EMAIL_REGEX },
             uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

SaleWebsite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

SaleWebsite/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

SaleWebsite/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Welcome to the Sale Website"
      redirect_to @user
    else
      render "new"
    end
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :sex,  :password_confirmation)
    end
end

SaleWebsite/app/helpers/application_helper.rb
module ApplicationHelper
end

SaleWebsite/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

SaleWebsite/app/helpers/users_helper.rb
module UsersHelper
end

SaleWebsite/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Sale Website", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path%></li>
            <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
</header>

SaleWebsite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaleWebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

SaleWebsite/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

SaleWebsite/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

SaleWebsite/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sale Website </h1>
  <%= link_to "Sign up now!",signup_path, class: "btn btn-lg btn-primary" %>
</div>

SaleWebsite/app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for@user, url: signup_path do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>